# file: postgresql/tasks/configure-common.yml
#
---
- name: Configure PostgreSQL client authentication
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0640"
    backup: true
  with_items:
    - { src: "pg_hba.conf.j2", dest: "{{ postgresql_conf_path }}/main/pg_hba.conf" }
  become: true
  notify:
    - Reload PostgreSQL
  tags:
    - postgresql:pg_hba

- name: Create PostgreSQL databases
  community.postgresql.postgresql_db:
    state: present
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default(omit) }}"
    lc_collate: "{{ item.lc_collate | default(omit) }}"
    lc_ctype: "{{ item.lc_ctype | default(omit) }}"
    template: "{{ item.template | default(omit) }}"
  with_items: "{{ postgresql_databases }}"
  become: true
  become_user: "{{ postgresql_user }}"

- name: Configure PostgreSQL users
  community.postgresql.postgresql_user:
    state: present
    name: "{{ item.name }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    conn_limit: "{{ item.connection_limit }}" # Should force a default here
  with_items: "{{ postgresql_users }}"
  become: true
  become_user: "{{ postgresql_user }}"

# This task deprecated by conn_limit arg in previous task.
# - name: Configure connection limit of PostgreSQL users
#   ansible.builtin.command: psql -U {{ postgresql_user }} -c 'ALTER ROLE {{ item.name }} WITH CONNECTION LIMIT {{ item.connection_limit }}'
#   with_items: "{{ postgresql_users }}"
#   when: "item.connection_limit is defined"
#   become: true
#   become_user: "{{ postgresql_user }}"

- name: Configure privileges of PostgreSQL users
  community.postgresql.postgresql_privs:
    state: present
    database: "{{ item.database }}"
    roles: "{{ item.roles }}"
    grant_option: "{{ item.grant_option | default(omit) }}"
    type: "{{ item.type | default(omit) }}"
    objs: "{{ item.objs | default(omit) }}"
    privs: "{{ item.privs | default(omit) }}"
    schema: "{{ item.schema | default(omit) }}"
  with_items: "{{ postgresql_privs }}"
  when: item.target is not defined
  become: true
  become_user: "{{ postgresql_user }}"

# See https://github.com/ansible/ansible-modules-core/issues/4493
# The above repo is deprecated, this task is probably obsolete
# - name: Configure default privileges of PostgreSQL users
#   ansible.builtin.command: |-
      # psql -U {{ postgresql_user }} \
      #      -c 'ALTER DEFAULT PRIVILEGES FOR USER {{ item.target }} \
      #          IN SCHEMA {{ item.schema | default("public") }} \
      #          GRANT {{ item.privs }} \
      #          ON {{ item.type }} \
      #          TO {{ item.roles }};'
#   with_items: "{{ postgresql_privs }}"
#   when: item.target is defined
#   become: true
#   become_user: "{{ postgresql_user }}"

- name: Configure PostgreSQL databases
  community.postgresql.postgresql_db:
    state: present
    name: "{{ item.name }}"
    owner: "{{ item.owner | default(omit) }}"
    encoding: "{{ item.encoding | default(omit) }}"
    lc_collate: "{{ item.lc_collate | default(omit) }}"
    lc_ctype: "{{ item.lc_ctype | default(omit) }}"
    template: "{{ item.template | default(omit) }}"
  with_items: "{{ postgresql_databases }}"
  become: true
  become_user: "{{ postgresql_user }}"

- name: Configure number of huge memory pages to be allocated
  ansible.posix.sysctl:
    name: vm.nr_hugepages
    value: "{{ postgresql_huge_pages_number }}"
    state: present
  when: postgresql_huge_pages_number is defined
  become: true

- name: Configure PostgreSQL
  ansible.builtin.template:
    src: "postgresql-{{ postgresql_version }}.conf.j2"
    dest: "{{ postgresql_conf_path }}/main/postgresql.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0644"
    backup: true
  # unnecessary loop - disabled
  # with_items:
  #   - src: "postgresql-{{ postgresql_version }}.conf.j2"
  #     dest: "{{ postgresql_conf_path }}/main/postgresql.conf"
  become: true
  notify:
    - Restart PostgreSQL

# This should be done with an assertion on an output
- name: Check if PostreSQL standby server is in recovery
  ansible.builtin.command: psql -U {{ postgresql_user }} -c 'SELECT pg_is_in_recovery();'
  when: "'dbstandby' in group_names"
  register: postgresql_is_in_recovery_status
  ignore_errors: true
  changed_when: false
  become: true
  become_user: "{{ postgresql_user }}"

- name: Register PostgreSQL standby server recovery status
  ansible.builtin.set_fact:
    postgresql_is_in_recovery: "{{ postgresql_is_in_recovery_status is success and postgresql_is_in_recovery_status.stdout_lines[2].find('t') == 1 }}"
  when: "'dbstandby' in group_names"

- name: Init Standby
  ansible.builtin.include_tasks: init-standby-common.yml
  when: "'dbstandby' in group_names and not postgresql_is_in_recovery"
