---
- name: Stop PostgreSQL
  ansible.builtin.service:
    name: "{{ postgresql_service }}"
    state: "stopped"
  become: true

- name: Remove PostgreSQL data dir
  ansible.builtin.file:
    path: "{{ postgresql_data_path }}/main"
    state: absent
  become: true

- name: Take base backup of PostgreSQL database
  ansible.builtin.shell: "{{ item }}" # noqa command-instead-of-shell
  environment:
    PGPASSWORD: "{{ postgresql_replication_password }}"
  become: true
  become_user: "{{ postgresql_user }}"
  changed_when: false
  with_items:
    - |-
      pg_basebackup \
        -h {{ postgresql_master_host }} \
        -p {{  postgresql_master_port }} \
        -D {{ postgresql_data_path }}/main \
        -U {{ postgresql_replication_user }} \
        -X stream \
        -R
    - sleep 15
# sleep should be a wait_for task after this one


- name: Configure PostgreSQL replication
  ansible.builtin.template:
    src: recovery.conf.j2
    dest: "{{ postgresql_data_path }}/main/recovery.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0640"
  become: true
  when: postgresql_version is version('12', '<')
