---
- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: "auto"

- name: "Run Initialise tasks"
  when: ('slapd' not in ansible_facts.packages or 'ldap-utils' not in ansible_facts.packages) or openldap_init
  block:
      # run these tasks only when initialise variable is true or slapd/ldap-utils are not installed
    - name: Define slapd installation settings
      ansible.builtin.debconf:
        name: "slapd"
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
      with_items:
        - question: 'slapd/no_configuration'
          value: 'false'
          vtype: 'boolean'
        - question: "slapd/purge_database"
          value: 'true'
          vtype: 'boolean'
        - question: "slapd/backend"
          value: 'MDB'
          vtype: 'string'
        - question: "slapd/move_old_database"
          value: 'true'
          vtype: 'boolean'
        - question: "slapd/domain"
          value: "{{ openbldap_pri_domain_name }}"
          vtype: 'string'
        - question: "shared/organization"
          value: "{{ openldap_org }}"
          vtype: 'string'
      become: true

    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ openldap_debian_packages }}"
        state: present
        install_recommends: false
        update_cache: true
        cache_valid_time: 86400
      become: true

    - name: Find /var/backups ending with .ldapdb or matching with slapd-*+*
      ansible.builtin.find:
        paths: /var/backups
        patterns: "*.ldapdb,slapd-*+*"
        file_type: directory
      become: true
      register: backup_files

    - name: Ensure /var/backups/openldap dir exists
      ansible.builtin.file:
        path: /var/backups/openldap
        state: directory
        owner: openldap
        group: openldap
        mode: "0755"
      become: true

    - name: Move Backup Files to another folder
      ansible.builtin.command: >-
        mv {{ item.path }} \
          /var/backups/openldap/{{ item.path | replace("/var/backups/", "") }}.{{ ansible_date_time.epoch }}
      with_items: "{{ backup_files.files }}"
      ignore_errors: true # noqa ignore-errors
      changed_when: false
      become: true

    - name: Reconfigure slapd # TODO - should be a handler
      ansible.builtin.command: dpkg-reconfigure -f noninteractive slapd
      changed_when: false
      become: true

    - name: Restart slapd # TODO - should be a handler
      ansible.builtin.systemd:
        name: slapd
        enabled: true
        daemon_reload: true
        state: restarted
      become: true
