---
# tasks file for ansible-openldap
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install Debian
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - install
    - openldap:install

- name: Configure
  ansible.builtin.include_tasks: configure.yml
  tags:
    - config
    - openldap:config

- name: Populate
  ansible.builtin.include_tasks: populate.yml
  tags:
    - openldap:populate
