# file: nginx/tasks/configure-ssl-cert.yml
#
---

- name: Ensure nginx SSL certificate directories exist
  ansible.builtin.file:
    path: "{{ item.certificate_file | dirname }}"
    owner: "{{ nginx_ssl_certificate_file_owner }}"
    group: "{{ nginx_ssl_certificate_file_group }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ nginx_vhosts }}"
  when: item.certificate_file is defined and item.certificate is defined
  become: true

- name: Ensure nginx SSL certificates are copied
  ansible.builtin.copy:
    dest: "{{ item.certificate_file }}"
    content: "{{ item.certificate }}"
    owner: "{{ nginx_ssl_certificate_file_owner }}"
    group: "{{ nginx_ssl_certificate_file_group }}"
    mode: "{{ nginx_ssl_certificate_file_mode }}"
    backup: true
  with_items:
    - "{{ nginx_vhosts }}"
  when: item.certificate_file is defined and item.certificate is defined
  become: true
  notify:
    - Restart nginx

- name: Ensure nginx SSL certificate key directories exist
  ansible.builtin.file:
    path: "{{ item.certificate_key_file | dirname }}"
    owner: "{{ nginx_ssl_certificate_key_file_owner }}"
    group: "{{ nginx_ssl_certificate_key_file_group }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ nginx_vhosts }}"
  when: item.certificate_key_file is defined and item.certificate_key is defined
  become: true

- name: Ensure nginx SSL certificate keys are copied
  ansible.builtin.copy:
    dest: "{{ item.certificate_key_file }}"
    content: '{{ item.certificate_key }}'
    owner: "{{ nginx_ssl_certificate_key_file_owner }}"
    group: "{{ nginx_ssl_certificate_key_file_group }}"
    mode: "{{ nginx_ssl_certificate_key_file_mode }}"
    backup: true
  with_items:
    - "{{ nginx_vhosts }}"
  when: item.certificate_key_file is defined and item.certificate_key is defined
  become: true
  no_log: true
  notify:
    - Restart nginx
