---

- name: Ensure nginx server is installed (Debian)
  ansible.builtin.apt:
    name:
      - nginx
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 86400
  become: true
