# file: rciam-probes/tasks/main.yml
#
---

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Install OS-specific packages
  ansible.builtin.include_tasks: install-RedHat.yml
  when: ansible_os_family == 'RedHat'
# - include: install-Debian.yml
#  when: ansible_os_family == 'Debian'

- name: Configure RedHat
  ansible.builtin.include_tasks: configure-RedHat.yml
  when: ansible_os_family == 'RedHat'
# - include: configure-Debian.yml
#  when: ansible_os_family == 'Debian'

# Tasks adding/copying/replacing files
- name: Include OS-independent Update/Copy tasks
  ansible.builtin.include_tasks:
    file: update-static.yml
    apply:
      tags:
        - update
  tags:
    - update
