---
# tasks file for fedreg-agent
- name: Install basic common utils
  ansible.builtin.package:
    name: "{{ item }}"
    state: preset
  loop:
    - git
    - python3-pip
  become: true
  tags:
    - agent
    - basic_common_utils

- name: Upgrade pip3
  ansible.builtin.pip:
    name: pip
    state: present
    extra_args: --upgrade --user
    executable: pip3
  become: true
  tags:
    - agent
    - python

- name: Install Virtualenv via pip3
  ansible.builtin.pip:
    name: virtualenv
    state: present
    executable: pip3
  become: true
  tags:
    - agent
    - python
