---
# tasks file for fedreg-agent
- name: Download only the requirements.txt from rciam-federation-registry-agent repository
  ansible.builtin.get_url:
    url: "{{ fedreg_agent_registry_requirements_url }}"
    dest: /tmp/requirements_{{ build_branch }}.txt
    mode: "0644"
  become: true
  tags:
    - agent
    - python
    - requirements

- name: Install python requirements
  ansible.builtin.pip:
    requirements: /tmp/requirements_{{ build_branch }}.txt
    virtualenv: "{{ fedreg_agent_venv_path }}"
    virtualenv_python: "{{ fedreg_agent_venv_python }}"
  become: true
  tags:
    - agent
    - python
    - requirements

# This should be packaged as a release instead of a branch
- name: Install rciam-federation-registry-agent (test.pypi.org)
  when: build_branch == "devel"
  ansible.builtin.pip:
    name: rciam-federation-registry-agent
    virtualenv: "{{ fedreg_agent_venv_path }}"
    virtualenv_python: "{{ fedreg_agent_venv_python }}"
    extra_args: -i https://test.pypi.org/simple/
    state: present
  become: true
  tags:
    - agent
    - python
    - requirements

# This should be packaged as a release instead of a branch
- name: Install rciam-federation-registry-agent
  when: build_branch == "master"
  ansible.builtin.pip:
    name: rciam-federation-registry-agent
    virtualenv: "{{ fedreg_agent_venv_path }}"
    virtualenv_python: "{{ fedreg_agent_venv_python }}"
    state: present
  become: true
  tags:
    - agent
    - python
    - requirements

- name: "Ensure dir exists: {{ fedreg_agent_conf_dir }}"
  ansible.builtin.file:
    path: "{{ fedreg_agent_conf_dir }}"
    state: directory
    mode: "0755"
  become: true
  tags:
    - agent
    - config

- name: Copy logger.conf file
  ansible.builtin.copy:
    src: logger.conf
    dest: "{{ fedreg_agent_conf_dir }}/logger.conf"
    force: false
    mode: "0644"
  become: true
  tags:
    - agent
    - config
