- name: Create deployer configuration file
  ansible.builtin.template:
    src: deployers.config.json.j2
    dest: "{{ fedreg_agent_conf_dir }}/{{ deployers_config_name }}"
    backup: true
    mode: "0644"
  when: fedreg_agent_enable_ssp or fedreg_agent_enable_mitreid or fedreg_agent_enable_keycloak
  become: true
  tags:
    - agent
    - config
  notify: Reload systemd

- name: Create MITREid deployer service file
  ansible.builtin.template:
    src: deployer_mitreid.service.j2
    dest: "{{ fedreg_agent_services_path }}/{{ deployer_mitreid_name }}.service"
    backup: true
    mode: "0644"
  register: mitreid_service
  when: fedreg_agent_enable_mitreid
  become: true
  tags:
    - agent
    - service
  notify: Reload systemd

- name: Create Keycloak deployer service file
  ansible.builtin.template:
    src: deployer_keycloak.service.j2
    dest: "{{ fedreg_agent_services_path }}/{{ deployer_keycloak_name }}.service"
    backup: true
    mode: "0644"
  register: keycloak_service
  when: fedreg_agent_enable_keycloak
  become: true
  tags:
    - agent
    - service
  notify: Reload systemd

- name: Create SSP deployer service file
  ansible.builtin.template:
    src: deployer_ssp.service.j2
    dest: "{{ fedreg_agent_services_path }}/{{ deployer_ssp_name }}.service"
    backup: true
    mode: "0644"
  register: ssp_service
  when: fedreg_agent_enable_ssp
  become: true
  tags:
    - agent
    - service
  notify: Reload systemd


- name: MitreId federation registry service enable
  ansible.builtin.service:
    name: '{{ deployer_mitreid_name }}'
    enabled: true
    state: restarted
  when: fedreg_agent_enable_mitreid
  become: true
  tags:
    - agent
    - service
    - service_enable

- name: Keycloak deployer service enable
  ansible.builtin.service:
    name: '{{ deployer_keycloak_name }}'
    enabled: true
    state: restarted
  when: fedreg_agent_enable_keycloak
  become: true
  tags:
    - agent
    - service
    - service_enable

- name: SSP federation registry service enable
  ansible.builtin.service:
    name: '{{ deployer_ssp_name }}'
    enabled: true
    state: restarted
  when: fedreg_agent_enable_ssp
  become: true
  tags:
    - agent
    - service
    - service_enable
