---
# keycloak/tasks/widlfly/install-plugin.yml
- name: Install widlfly plugin
  when: not item is undefined
  become: true
  tags: "keycloak:install:plugins"
  ansible.builtin.block:
    - name: "Installing plugin as a module: {{ item.value.name }}"
      ansible.builtin.block:
        - name: "Create plugin dir with parent directories (for plugin: {{ item.value.name }})"
          ansible.builtin.file:
            path: "{{ keycloak_home }}/modules/system/layers/keycloak/org/keycloak/{{ item.value.name }}/main"
            state: directory
            mode: "0755"

        - name: "Download plugin jar (of plugin: {{ item.value.name }})"
          ansible.builtin.get_url:
            url: "{{ item.value.module.jar_url }}"
            dest: "{{ keycloak_home }}/modules/system/layers/keycloak/org/keycloak/{{ item.value.name }}/main/"
            mode: "0644"

        - name: "Install module.xml (for plugin: {{ item.value.name }})"
          ansible.builtin.get_url:
            url: "{{ item.value.module.modulexml_url }}"
            dest: "{{ keycloak_home }}/modules/system/layers/keycloak/org/keycloak/{{ item.value.name }}/main/"
            mode: "0644"

        - name: "Setup keycloak xml providers (for plugin: {{ item.value.name }})"
          community.general.xml:
            path: "{{ keycloak_home }}/standalone/configuration/standalone-ha.xml"
            xpath: /srv:server/srv:profile/sub:subsystem/sub:providers
            input_type: xml
            add_children:
              - "<provider>module:org.keycloak.{{ item.value.name }}</provider>"
            namespaces:
              srv: "{{ namespaces.domain }}"
              sub: "{{ namespaces.domain_server }}"

        - name: "Setup keycloak xml theme modules (for plugin: {{ item.value.name }})"
          community.general.xml:
            path: "{{ keycloak_home }}/standalone/configuration/standalone-ha.xml"
            xpath: /srv:server/srv:profile/sub:subsystem/sub:theme
            input_type: xml
            add_children:
              - "<modules>  <module>org.keycloak.{{ item.value.name }}</module>  </modules>"
            namespaces:
              srv: "{{ namespaces.domain }}"
              sub: "{{ namespaces.domain_server }}"
          when: item.value.theme is defined
      when: item.value.module is defined

    - name: "Installing plugin with hot deploy: {{ item.value.name }}"
      block:
        - name: "Download plugin jar into folder /tmp (for plugin: {{ item.value.name }})"
          ansible.builtin.get_url:
            url: "{{ item.value.hotdeploy.jar_url }}"
            dest: "/tmp/"
          register: download_result
        # do not download directly to deployment folder (if it's downloaded slowly or the file is large, the deployment might be broken)
        - name: "Move into deployment folder (for plugin: {{ item.value.name }})"
          ansible.builtin.command: "mv {{ download_result.dest }} {{ keycloak_home }}/standalone/deployments/"

      when: item.value.hotdeploy is defined
