---
# egi-igtf/tasks/configure-Debian.yml
- name: Ensure dir for EGI Trust Anchor symlinks exists  (Debian)
  ansible.builtin.file:
    path: /usr/local/share/ca-certificates/egi-igtf
    state: directory
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Register EGI Trust Anchors to symlink (Debian)
  ansible.builtin.shell: "ls /etc/grid-security/certificates/*.0" # noqa
  register: egi_igtf_certs
  changed_when: false

- name: Ensure symlinks to EGI Trust Anchors exist (Debian)
  ansible.builtin.file:
    path: "/usr/local/share/ca-certificates/egi-igtf/{{ item | basename }}.crt"
    src: "{{ item }}"
    state: link
  with_items: "{{ egi_igtf_certs.stdout_lines }}"
  register: egi_igtf_cert_symlinks
  become: true
  notify: Update certs
