---
- name: Ensure EUGridPMA apt key is installed (Debian)
  ansible.builtin.apt_key:
    url: "{{ egi_igtf_repo_key_url }}"
    state: present
  become: true

- name: Ensure EGI Trust Anchor repository is included (Debian)
  ansible.builtin.apt_repository:
    repo: "deb {{ egi_igtf_repo_url }} egi-igtf {{ egi_igtf_components }}"
    state: present
  become: true

- name: Ensure latest versions of EGI Trust Anchors are installed (Debian)
  ansible.builtin.apt:
    name: ca-policy-egi-core # This really needs a version attached to it!
    state: present
    update_cache: true
  become: true
