---
# egi-igtf/tasks/main.yml
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Run OS-specific installation tasks
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Apply OS-specific configuration
  ansible.builtin.include_tasks: configure-Debian.yml
  when: ansible_os_family == 'Debian'
