---
- name: Ensure sites-available and sites-enabled directories exist (RedHat)
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0775"
  loop:
    - "{{ apache_conf_path }}/sites-available"
    - "{{ apache_conf_path }}/sites-enabled"

- name: Append extra parameters into Apache httpd.conf (RedHat)
  become: true
  ansible.builtin.blockinfile:
    path: "{{ apache_conf_path }}/conf/httpd.conf"
    block: |
      IncludeOptional sites-enabled/*.conf
      IncludeOptional conf.d/security.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Restart apache

- name: Configure Apache security settings (RedHat)
  become: true
  ansible.builtin.template:
    src: security.conf.j2
    dest: "{{ apache_conf_path }}/conf.d/security.conf"
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Restart apache

# Configure Virtual Host SSL certificates
- name: Include vhost SSL certificates configuration
  become: true
  ansible.builtin.include_tasks: configure-ssl-cert.yml
  when: apache_create_vhosts and apache_vhosts_ssl is defined and apache_vhosts_ssl|length > 0

- name: Add Apache vhosts configuration (RedHat)
  become: true
  ansible.builtin.template:
    src: vhosts.conf.j2
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Restart apache
  when: apache_create_vhosts

- name: Enable Apache vhosts configuration (RedHat)
  become: true
  ansible.builtin.file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  notify: Restart apache
  when: apache_create_vhosts

- name: Disable default welcome page (RedHat)
  become: true
  ansible.builtin.file:
    path: "{{ apache_conf_path }}/conf.d/welcome.conf"
    state: absent
  when: apache_remove_default_page
  notify: Restart apache

- name: Enable required Apache modules (RedHat)
  become: true
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items: "{{ apache_mods_enabled }}"
  notify: Restart apache

- name: Disable unnecessary Apache modules (RedHat)
  become: true
  community.general.apache2_module:
    state: absent
    name: "{{ item }}"
  with_items: "{{ apache_mods_disabled }}"
  notify: Restart apache
