---
- name: Enable required Apache modules (Debian)
  become: true
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items: "{{ apache_mods_enabled }}"
  notify:
    - Restart apache

- name: Disable unnecessary Apache modules (Debian)
  become: true
  community.general.apache2_module:
    state: absent
    name: "{{ item }}"
  with_items: "{{ apache_mods_disabled }}"
  notify:
    - Restart apache

- name: Remove default vhost from sites-enabled (Debian)
  become: true
  ansible.builtin.file:
    path: "{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhost_filename }}"
    state: absent
  notify: Restart apache
  when: apache_remove_default_vhost

- name: Configure Apache ports (Debian)
  become: true
  ansible.builtin.template:
    src: ports.conf.j2
    dest: "{{ apache_conf_path }}/ports.conf"
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Restart apache

- name: Configure Apache security settings (Debian)
  become: true
  ansible.builtin.template:
    src: security.conf.j2
    dest: "{{ apache_conf_path }}/conf-available/security.conf"
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Restart apache

- name: Enable Apache security configuration (Debian)
  become: true
  ansible.builtin.file:
    src: "{{ apache_conf_path }}/conf-available/security.conf"
    dest: "{{ apache_conf_path }}/conf-enabled/security.conf"
    state: link
  notify: Restart apache

- name: Add Apache vhosts configuration (Debian)
  become: true
  ansible.builtin.template:
    src: vhosts.conf.j2
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Restart apache
  when: apache_create_vhosts

- name: Enable Apache vhosts configuration (Debian)
  become: true
  ansible.builtin.file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  notify: Restart apache
  when: apache_create_vhosts
