---
- name: Ensure Apache HTTP server is installed (Debian)
  ansible.builtin.apt:
    name: apache2
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 86400
  become: true

- name: Install Modules for Apache
  ansible.builtin.apt:
    name: "{{ apache_mods_installed }}"
    state: present
  become: true
  notify: Restart apache
