---
- name: Ensure Apache HTTP server is installed (Redhat)
  ansible.builtin.yum:
    name: httpd
    state: present
    update_cache: true
  become: true
  notify:
    - restart apache

- name: Ensure Apache ssl module is installed (Redhat)
  ansible.builtin.yum:
    name: mod_ssl
    state: present
    update_cache: true
  become: true
  when: apache_vhosts_ssl is defined and apache_vhosts_ssl|length > 0
  notify:
    - restart apache
