---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
- include: install-Debian.yml
  when: ansible_os_family == 'Debian'
- include: install-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Apply OS-specific configuration
- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'
- include: configure-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure Apache service is at selected state and enabled on boot
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: true
  become: true
