---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure Debian Installation
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure RedHat Installation
  ansible.builtin.include_tasks: install-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Could be refactored as:
# - name: Include install tasks
#   ansible.builtin.include_tasks: "install-{{ ansible_os_family }}.yml"

# Apply OS-specific configuration
- name: Include Debian Configuration Tasks
  ansible.builtin.include_tasks: configure-Debian.yml
  when: ansible_os_family == 'Debian'
- name: Include RedHat Configuration tasks
  ansible.builtin.include_tasks: configure-RedHat.yml
  when: ansible_os_family == 'RedHat'
# Could be refactored as:
# - name: Include Configuration tasks
#   ansible.builtin.include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: Ensure Apache service is at selected state and enabled on boot
  become: true
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: true
