# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: requirements-txt-fixer

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
    - id: detect-secrets
      args:
        - --baseline
        - .secrets.baseline

- repo: https://github.com/ansible-community/ansible-lint
  rev: v24.2.1
  hooks:
    - id: ansible-lint
      always_run: false
      files: ^.*.yml
      exclude: .github
      additional_dependencies:
        - ansible-core>=2.16.0
      args:
        - --exclude
        - .pre-commit-config.yaml
        - icingaagents.yml
        # For some reason noqa is not being picked up on these files
        - roles/common/handlers/main.yml
        - authzkeys.yml
        # ssp-modules is a bad name for a role
        - roles/ssp-modules

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.0
  hooks:
    - id: check-github-workflows
    - id: check-dependabot
