# file: cert2samlservers.yml
#
---
- name: Deploy Certificate to SML servers
  hosts: cert2saml
  roles:
    - { role: apache, tags: apache }
    - { role: php, tags: php }
    - { role: ssp, tags: ssp }
    - { role: ssp-modules, tags: ssp-modules }
