# file: cmrolesuiservers.yml
---
- name: Deploy Comanage registry UI
  hosts: registry
  roles:
    - { role: git, tags: git }
    - { role: apache, tags: apache }
    - { role: php, tags: php }
    - { role: shibboleth-sp, tags: shibboleth-sp }
    - { role: cm-role-ui, tags: cm-role-ui }
