# file: oauth2samlservers.yml
#
---

- name: Deploy Oauth2Saml
  hosts: oauth2saml
  roles:
    - { role: ssp, tags: ssp }
    - { role: ssp-modules, tags: ssp-modules }
  tasks:
    - name: Install modules using composer
      # shell: php composer.phar require oakhope/oauth2-wechat --ignore-platform-reqs --no-interaction --no-scripts
      ansible.builtin.shell: >- # Better to declare dependencies here
        php composer.phar require \
          cirrusidentity/simplesamlphp-module-authoauth2:v3.1.0 \
          league/oauth2-google \
          oakhope/oauth2-wechat \
          --ignore-platform-reqs \
          --no-interaction \
          --no-scripts
      args:
        chdir: "{{ ssp_path }}/"
        executable: /bin/bash
      register: composer_results
      changed_when: composer_results is changed and "Nothing to install, update or remove" not in composer_results.stderr
      when: ssp_mods_extra_enabled | selectattr('name', 'equalto', 'authoauth2') | list | count > 0
      become: true
      tags:
        - install
        - install-composer
        - ssp:install
        - ssp:install:mods
        - ssp-modules:install
