# file: rciam-keycloak.yml
# RCIAM deployment based on Keycloak
---

- name: Run Firewall Servers
  ansible.builtin.import_playbook: firewallservers.yml

- name: Deploy DBN Servers
  ansible.builtin.import_playbook: dbservers.yml

- name: Deploy Keycloak servers
  ansible.builtin.import_playbook: keycloakservers.yml

- name: Deploy Web Proxy Servers
  ansible.builtin.import_playbook: webproxyservers.yml
