# file: saml2oidcservers.yml
#
---

- name: Deploy SAML 2 OIDC
  hosts: saml2oidc
  roles:
    - { role: jq, tags: jq }
    # - { role: ansiblebit.oracle-java, tags: java }
    - { role: infOpen.openjdk-jdk, tags: java }
    - { role: tomcat, tags: tomcat }
