---

ssp_module_proxystatistics_version: "rciam-3.0"

ssp_module_proxystatistics_path: "{{ ssp_path }}/modules/proxystatistics"

ssp_module_proxystatistics_repo_url: "https://github.com/rciam/proxystatistics-simplesamlphp-module.git"
ssp_module_proxystatistics_repo_version: "{{ ssp_module_proxystatistics_version }}"

# One of the following modes: "PROXY", "IDP", "SP"
ssp_module_proxystatistics_mode: "PROXY"

# REQUIRED FOR "IDP" MODE
# EntityId of IdP
# ssp_module_proxystatistics_idp_entity_id: "https://idp.example.org"
# Name of IdP
# ssp_module_proxystatistics_idp_entity_name: "IDP NAME"

# REQUIRED FOR "SP" MODE
# EntityId of SP
# ssp_module_proxystatistics_sp_entity_id: "https://sp.example.org"
# Name of SP
# ssp_module_proxystatistics_sp_entity_name: "SP NAME"

ssp_module_proxystatistics_db:
  name: "STATS"
  dsn: "mysql:host=localhost;port=3306;dbname=STATS;charset=utf8"
  username: "stats"
  password: "stats"
  prefix: ""
  persistent: false
  # slaves:
  #  - dsn: "mysql:host=slavedbhost;port=3306;dbname=STATS;charset=utf8"
  #    username: "stats"
  #    password: "stats"
  #    persistent: no

ssp_module_proxystatistics_detailed_days: 0

ssp_module_proxystatistics_user_id_attribute: "uid"

ssp_module_proxystatistics_table_name:
  statistics: "statistics"
  detailed_statistics: "statistics_detail"
  identity_providers_map: "identityProvidersMap"
  service_providers_map: "serviceProvidersMap"

ssp_module_proxystatistics_oidc_issuer: "http://example.org/openidconnect/sp"

# Ignore from statistics calculations the list of identifiers below.
# ssp_module_proxystatistics_user_id_blacklist:
#  - xxxxxx@example.org
