---
- name: Ensure COmanage Registry root directory exists
  ansible.builtin.file:
    path: "{{ comanage_root_dir }}"
    state: directory
    owner: root
    group: root
  become: true

- name: Ensure COmanage Registry source is cloned under root directory
  ansible.builtin.git:
    repo: "{{ comanage_repo }}"
    dest: "{{ comanage_root_dir }}/comanage-registry-{{ comanage_version }}"
    version: "{{ comanage_version }}"
    accept_hostkey: true
  ignore_errors: true
  become: true

- name: Ensure symbolic link to current COmanage Registry installation exists
  ansible.builtin.file:
    src: "{{ comanage_root_dir }}/comanage-registry-{{ comanage_version }}"
    dest: "{{ comanage_path }}"
    force: true
    state: link
    owner: root
    group: root
  become: true

- name: Ensure COmanage Registry webroot directory exists
  ansible.builtin.file:
    src: "{{ comanage_path }}/app/webroot"
    dest: "{{ comanage_webroot }}"
    state: link
    force: true
    owner: root
    group: root
  become: true

- name: Ensure COmanage Registry temp directory tree is initialised
  ansible.builtin.command: cp -r {{ comanage_path }}/app/tmp.dist {{ comanage_temp_dir }}
  args:
    creates: "{{ comanage_temp_dir }}"
  become: true

- name: Ensure COmanage Registry temp directory exists and is writable by webserver only
  ansible.builtin.file:
    path: "{{ comanage_temp_dir }}"
    state: directory
    owner: "{{ comanage_webserver_user }}"
    group: "{{ comanage_webserver_group }}"
    mode: "0700"
    recurse: true
  become: true

- name: Ensure link to COmanage Registry temp directory exists
  ansible.builtin.file:
    src: "{{ comanage_temp_dir }}"
    dest: "{{ comanage_path }}/local/tmp"
    state: link
    owner: root
    group: root
    follow: false
  become: true
