---
- name: Register COmanage files to be copied
  ansible.builtin.find:
    paths: "{{ inventory_dir }}/files/comanage-registry"
    file_type: file
    recurse: true
  register: comanage_files
  ignore_errors: true
  delegate_to: 127.0.0.1
  vars:
    ansible_connection: local

- name: Display files to be copied
  ansible.builtin.debug:
    msg: "{{ comanage_path }}/{{ item.path | regex_replace('(.*)[/]files[/]comanage-registry[/](.*)', '\\2') }}"
    verbosity: 1
  loop: "{{ comanage_files.files }}"
  loop_control:
    label: Copied file {{ item.path }}
  when: comanage_files is defined

- name: Copy COmanage files
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ comanage_path }}/{{ item.path | regex_replace('(.*)[/]files[/]comanage-registry[/](.*)', '\\2') }}"
    force: true
    owner: root
    mode: "0664"
    backup: true
  loop: "{{ comanage_files.files }}"
  loop_control:
    label: Added file {{ comanage_path }}/{{ item.path | regex_replace('(.*)[/]files[/]comanage-registry[/](.*)', '\2') }}
  become: true
  ignore_errors: true # noqa ignore-errors
  when: comanage_files is defined
