---
- name: Ensure Shibboleth SP SSL certificate is copied
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: "{{ shibboleth_sp_user }}"
    group: "{{ shibboleth_sp_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - content: "{{ shibboleth_sp_ssl_cert }}"
      dest: "{{ shibboleth_sp_conf_path }}/cert/sp-crt.pem"
      mode: "0644"
    - content: "{{ shibboleth_sp_ssl_cert_key }}"
      dest: "{{ shibboleth_sp_conf_path }}/cert/sp-key.pem"
      mode: "0600"
  when: not (shibboleth_sp_ssl_cert_generate|bool)
  become: true
  no_log: true
  notify:
    - Restart Shibboleth SP

- name: Ensure Shibboleth SP self-signed certificate is generated
  # This should probably use one of the modules from community.crypto
  ansible.builtin.command: |-
    openssl req \
      -newkey rsa:2048 -new -x509 -days 3652 \
      -subj "{{ shibboleth_sp_ssl_cert_subj }}" \
      -nodes -out sp-crt.pem -keyout sp-key.pem
  args:
    chdir: "{{ shibboleth_sp_conf_path }}/cert"
    creates: "{{ shibboleth_sp_conf_path }}/cert/sp-key.pem"
  when: shibboleth_sp_ssl_cert_generate|bool
  become: true
  notify:
    - Restart Shibboleth SP

- name: Ensure Shibboleth SP certificate is installed
  ansible.builtin.file:
    state: file
    path: "{{ item.path }}"
    owner: "{{ shibboleth_sp_user }}"
    group: "{{ shibboleth_sp_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - path: "{{ shibboleth_sp_conf_path }}/cert/sp-crt.pem"
      mode: "0644"
    - path: "{{ shibboleth_sp_conf_path }}/cert/sp-key.pem"
      mode: "0600"
  become: true

- name: Configure Shibboleth SP main settings
  ansible.builtin.template:
    src: shibboleth2.xml.j2
    dest: "{{ shibboleth_sp_conf_path }}/shibboleth2.xml"
    owner: root
    group: root
    mode: "0644"
    backup: true
  become: true
  notify:
    - Restart Shibboleth SP

- name: Configure Shibboleth SP attribute mappings
  ansible.builtin.copy:
    src: "{{ shibboleth_sp_attribute_map_file }}"
    dest: "{{ shibboleth_sp_conf_path }}/attribute-map.xml"
    owner: root
    group: root
    mode: "0644"
    backup: true
  when: shibboleth_sp_attribute_map_file is defined
  become: true
  notify:
    - Restart Shibboleth SP

- name: Configure Shibboleth SP attribute policies
  ansible.builtin.copy:
    src: "{{ shibboleth_sp_attribute_policy_file }}"
    dest: "{{ shibboleth_sp_conf_path }}/attribute-policy.xml"
    owner: root
    group: root
    mode: "0644"
    backup: true
  when: shibboleth_sp_attribute_policy_file is defined
  become: true
  notify:
    - Restart Shibboleth SP
