---
- name: Ensure Shibboleth SP Apache module is installed (Debian)
  ansible.builtin.apt:
    name: libapache2-mod-shib2
    state: present
    update_cache: true
    install_recommends: false
  become: true
