# file: rciam-utils/tasks/install-Debian.yml
#
---

- name: Ensure util dependencies are installed
  ansible.builtin.apt:
    name:
      - git
      - python3-venv
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 86400
  become: true

- name: Ensure PPA is installed for MaxMind (required for rciam-ip2country)
  ansible.builtin.apt_repository:
    repo: 'ppa:maxmind/ppa'
    state: present
    update_cache: true
    codename: trusty
  when:
    - rciam_utils | selectattr("name", "equalto", "rciam-ip2country") | list | length == 1
    - rciam_utils_ip2country.db_file_extension is defined and rciam_utils_ip2country.db_file_extension == "dat"
  become: true

- name: Ensure dependencies for rciam-ip2country are installed
  ansible.builtin.apt:
    name:
      - build-essential
      - python3-dev
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 86400
  when:
    - rciam_utils | selectattr("name", "equalto", "rciam-ip2country") | list | length == 1
  become: true

- name: Ensure additional dependencies for rciam-ip2country (legacy version only) are installed
  ansible.builtin.apt:
    name:
      - libgeoip1
      - libgeoip-dev
      - geoip-bin
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 86400
  when:
    - rciam_utils | selectattr("name", "equalto", "rciam-ip2country") | list | length == 1
    - rciam_utils_ip2country.db_file_extension is defined and rciam_utils_ip2country.db_file_extension == "dat"
  become: true
