# file: tasks/install-common.yml
---

- name: Ensure util groups exist
  ansible.builtin.group:
    name: "{{ item.user.group }}"
    system: true
  loop: "{{ rciam_utils }}"
  become: true

- name: Ensure util users exist
  ansible.builtin.user:
    name: "{{ item.user.name }}"
    groups: "{{ item.user.group }}"
    comment: "{{ item.user.gecos }}"
    shell: "{{ item.user.shell }}"
    home: "{{ item.user.path }}"
    system: true
    create_home: true
    skeleton: "/empty"
  loop: "{{ rciam_utils }}"
  become: true

- name: Ensure util code checkouts are up-to-date
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.path }}"
    version: "{{ item.version }}"
  loop: "{{ rciam_utils }}"
  become: true
  become_user: "{{ item.user.name }}"

- name: Ensure util python requirements are installed in virtualenvs
  ansible.builtin.pip:
    requirements: "{{ item.path }}/requirements.txt"
    virtualenv: "{{ item.path }}/.venv"
    virtualenv_command: python3 -m venv
    state: present
  loop: "{{ rciam_utils }}"
  become: true
  become_user: "{{ item.user.name }}"
