# file: tasks/main.yml
#
---
- name: Include OS-specific installation tasks
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'
# - include: install-RedHat.yml
#  when: ansible_os_family == 'RedHat'
  tags:
    - install
    - rciam_utils:install

- name: Include OS-independent installation tasks
  ansible.builtin.include_tasks: install-common.yml
  tags:
    - install
    - rciam_utils:install

- name: Include OS-independent configuration tasks
  ansible.builtin.include_tasks: configure.yml
  tags:
    - config
    - rciam_utils:config
