---
# keycloak/tasks/quarkus/install_plugin.yml
- name: Why do we have this block?
  become: true
  when: not item is undefined
  tags: "keycloak:install:plugins"
  block:
    - name: "Installing plugin with hot deploy: {{ item.value.name }}"
      when: item.value.hotdeploy is defined
      block:
        - name: "Download plugin jar into folder /tmp (for plugin: {{ item.value.name }})"
          ansible.builtin.get_url:
            url: "{{ item.value.hotdeploy.jar_url }}"
            dest: "/tmp/"
            mode: "0644"
          register: download_result
        # do not download directly to deployment folder (if it's downloaded slowly or the file is large, the deployment might be broken)
        - name: "Move into deployment folder (for plugin: {{ item.value.name }})"
          ansible.builtin.command: "mv {{ download_result.dest }} {{ keycloak_home }}/providers/"
          notify: Clear Keycloak cache # This is a really bad idea
          changed_when: true # Gonna have to trigger this always
