---

- block:

    - name: "Installing plugin {{ item.value.name }} with hot deploy"
      block:
        - name: "Download plugin jar into folder /tmp (for plugin: {{ item.value.name }})"
          get_url:
            url: "{{ item.value.hotdeploy.jar_url }}"
            dest: "/tmp/"
          register: download_result
        #do not download directly to deployment folder (if it's downloaded slowly or the file is large, the deployment might be broken)
        - name: "Move into deployment folder (for plugin: {{ item.value.name }})"
          command: "mv {{download_result.dest}} {{keycloak_home}}/providers/"
          notify: Clear Keycloak cache
      when: item.value.hotdeploy is defined

  when: not item is undefined
  become: yes
  tags: "keycloak:install:plugins"