# file: tasks/configure-local.yml
---
# After creating react configuration, github action will move the file to the react application
# before building
- name: Create react configuration file locally
  ansible.builint.template:
    src: react/config.json.j2
    dest: "{{ inventory_dir }}/files/config.{{ item.tenant }}.json"
    mode: "0400"
    backup: true
  loop: "{{ metrics_config | default([]) }}"
  when: item.frontend is defined
  no_log: true
  delegate_to: localhost
