# file: metrics/tasks/install-Debian.yml
#
---
- name: Ensure metrics dependencies are installed
  ansible.builtin.apt:
    name: # Should be declared in defaults
      - git
      - python3-venv
      - build-essential
      - python3-dev
      - python3-pip
      - nginx
      - python3-virtualenv
      - libpq-dev
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 86400
  become: true
