---
- name: Include OS-specific installation tasks
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - rciam-metrics:install

- name: Include OS-independent installation tasks
  ansible.builtin.import_tasks: bootstrap.yml
  tags:
    - rciam-metrics:bootstrap

# NOTE: The first time this task has to run manually using the --extra-var parameter
#  of ansible cmd command
# e.g. ansible-playbook -u debian
#                       -i inventories/rciam-metrics/hosts.ini
#                       metricsservers.yml
#                       --ask-vault-pass
#                       --tags "rciam-metrics:deploy-backend"
#                       --extra-vars metrics_release="metrics-api-deploy_changes-rc-deploy_changes-6335295151"
#                       --diff
#                       --check
- name: Include OS-independent configuration tasks
  ansible.builtin.import_tasks: deploy-backend.yml
  tags:
    - rciam-metrics:deploy-backend

  # NOTE: Runs through github actions ONLY
- name: Include OS-independent configuration tasks
  ansible.builtin.import_tasks: configure-local.yml
  tags:
    - rciam-metrics:config-local

  # NOTE: Runs through github actions ONLY
- name: Include OS-independent configuration tasks
  ansible.builtin.import_tasks: deploy-frontend.yml
  tags:
    - rciam-metrics:deploy-frontend
