# file: tasks/configure.yml
---
- name: Configure webapp
  ansible.builtin.template:
    src: "{{ item.src_config_path }}"
    dest: "{{ item.dest_config_path }}"
    backup: true
    mode: "0644"
  loop: "{{ rciam_oidc_clients }}"
  become: true
