# file: rciam-oidc-client/tasks/install-common-client.yml
#
---

- name: Create RCIAM OIDC Client temp directory
  ansible.builtin.file:
    path: "/tmp/{{ item.item.name }}"
    state: directory
    mode: "0755"
  become: true

- name: Download & unarchive RCIAM OIDC Client to temp directory
  ansible.builtin.unarchive:
    src: "{{ item.item.release }}"
    dest: "/tmp/{{ item.item.name }}"
    remote_src: true
    list_files: true
  register: rciam_oidc_client_unarchive
  become: true

- name: Setting RCIAM OIDC Client temp directory
  ansible.builtin.set_fact:
    rciam_oidc_client_tmp_dir: "/tmp/{{ item.item.name }}/{{ rciam_oidc_client_unarchive.files[0].split('/')[0] }}"

- name: Backup old version of RCIAM OIDC Client
  ansible.builtin.command:
    cmd: "mv {{ item.item.path }} {{ item.item.path }}.{{ ansible_date_time.iso8601 }}"
    removes: "{{ item.item.path }}"
  become: true

- name: Move RCIAM OIDC Client from temp directory to target path
  ansible.builtin.command: "mv {{ rciam_oidc_client_tmp_dir }} {{ item.item.path }}"
  changed_when: false
  become: true

- name: Create a file with the version of the RCIAM OIDC Client
  ansible.builtin.copy:
    content: ""
    dest: "{{ item.item.path }}/{{ item.item.version }}"
    force: false
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Ensure RCIAM OIDC Client temp directory is absent
  ansible.builtin.file:
    path: "/tmp/{{ item.item.name }}"
    state: absent
  become: true
