# file: rciam-oidc-client/tasks/main.yml
#
---
- name: Include OS-specific installation tasks
  ansible.builtin.include_tasks: install-common.yml
  tags:
    - install

- name: Include OS-independent configuration tasks
  ansible.builtin.include_tasks: configure-common.yml
  tags:
    - config
