---
- name: Create installation directory for composer
  ansible.builtin.file:
    state: directory
    path: "{{ ssp_composer_install_directory }}"
    mode: "0644"
  become: true
  tags:
    - ssp:install
    - ssp:install:composer

- name: Check if exist composer executable exists
  ansible.builtin.stat:
    path: "{{ ssp_composer_executable }}"
  register: composer_exists
  become: true
  tags:
    - ssp:install
    - ssp:install:composer

# Use uri here
- name: Download composer # noqa command-instead-of-module no-changed-when
  ansible.builtin.command: curl -sS https://getcomposer.org/installer -o composer-setup.php
  args:
    chdir: "{{ ssp_composer_install_directory }}"
  when: not composer_exists.stat.exists
  become: true
  tags:
    - ssp:install
    - ssp:install:composer
  creates: "{{ ssp_composer_install_directory }}/composer-setup.php"

# Use uri here
- name: Generate composer hash # noqa command-instead-of-module
  ansible.builtin.command: curl -sS https://composer.github.io/installer.sig
  register: composerhash
  when: not composer_exists.stat.exists
  become: true
  tags:
    - ssp:install
    - ssp:install:composer
  changed_when: false # noqa no-changed-when

- name: Print composer hash
  ansible.builtin.debug:
    msg: "Composer hash is: {{ composerhash.stdout }}"
  when: composerhash.stdout is defined
  become: true
  tags:
    - ssp:install
    - ssp:install:composer

- name: Verify composer # noqa command-instead-of-module
  ansible.builtin.command: |-
    php -r \
      "if (hash_file('SHA384', 'composer-setup.php') === '{{ composerhash.stdout }}') \
        { echo 'Installer verified'; }  \
      else \
      { echo 'Installer corrupt'; unlink('composer-setup.php'); } \
      echo PHP_EOL;"
  args:
    chdir: "{{ ssp_composer_install_directory }}"
  when: not composer_exists.stat.exists
  become: true
  tags:
    - ssp:install
    - ssp:install:composer
  changed_when: false
  failed_when: false1

# Use community.general.composer here
- name: Composer setup # noqa no-changed-when
  ansible.builtin.command: php composer-setup.php
  args:
    chdir: "{{ ssp_composer_install_directory }}"
  when: not composer_exists.stat.exists
  become: true
  tags:
    - ssp:install
    - ssp:install:composer
  changed_when: false

- name: Move Composer globally # noqa no-changed-when
  ansible.builtin.command: mv composer.phar {{ ssp_composer_executable }}
  args:
    chdir: "{{ ssp_composer_install_directory }}"
  become: true
  when: not composer_exists.stat.exists
  tags:
    - ssp:install
    - ssp:install:composer

- name: Set permissions on Composer
  ansible.builtin.file:
    path: "{{ ssp_composer_executable }}"
    mode: a+x
  become: true
  tags:
    - ssp:install
    - ssp:install:composer
