---

- name: Create installation directory for composer
  file:
    state: directory
    path: '{{ composer_install_directory }}'
  become: yes
  tags:
    - ssp:install
    - ssp:install:composer

- name: check if exist composer.phar
  stat:
    path: '{{ composer_install_directory }}/composer.phar'
  register: composer_exists
  become: yes
  tags:
    - ssp:install
    - ssp:install:composer

- name: Download composer
  ansible.builtin.command: curl -sS https://getcomposer.org/installer -o composer-setup.php
  args:
    chdir: '{{ composer_install_directory }}'
  when: composer_exists.stat.exists == False
  become: yes
  tags:
    - ssp:install
    - ssp:install:composer

- name: Generate composer hash
  ansible.builtin.command: curl -sS https://composer.github.io/installer.sig
  register: composerhash
  when: composer_exists.stat.exists == False
  become: yes
  tags:
    - ssp:install
    - ssp:install:composer

- name: Print composer hash
  ansible.builtin.debug:
    msg: "Composer hash is: {{ composerhash.stdout }}"
  when: composerhash.stdout is defined
  become: yes
  tags:
    - ssp:install
    - ssp:install:composer

- name: Verify composer
  command: php -r "if (hash_file('SHA384', 'composer-setup.php') === '{{ composerhash.stdout }}') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  args:
    chdir: '{{ composer_install_directory }}'
  when: composer_exists.stat.exists == False
  become: yes
  tags:
    - ssp:install
    - ssp:install:composer

- name: Composer setup
  ansible.builtin.command: php composer-setup.php
  args:
    chdir: '{{ composer_install_directory }}'
  when: composer_exists.stat.exists == False
  become: yes
  tags:
    - ssp:install
    - ssp:install:composer

- name: Move Composer globally
  ansible.builtin.command: mv composer.phar /usr/local/bin/composer
  args:
    chdir: '{{ composer_install_directory }}'
  become: yes
  tags:
    - ssp:install
    - ssp:install:composer

- name: Set permissions on Composer
  ansible.builtin.file:
    path: /usr/local/bin/composer
    mode: "a+x"
  become: yes
  tags:
    - ssp:install
    - ssp:install:composer
