---

- name: Configure SSP hosted SAML 1.1 IdP metadata
  template:
    src: "{{ item }}"
    dest: "{{ ssp_metadatadir }}/shib13-idp-hosted.php"
    backup: yes
    force: yes
  with_first_found:
    - "metadata/shib13-idp-hosted-{{ ssp_major_version }}.{{ ssp_minor_version }}.php.j2"
    - "metadata/shib13-idp-hosted-{{ ssp_major_version }}.php.j2"
    - "metadata/shib13-idp-hosted.php.j2"
  become: yes
