---
- name: Configure SSP hosted SAML 2.0 IdP metadata
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ ssp_metadatadir }}/saml20-idp-hosted.php"
    backup: true
    force: true
    mode: "0600"
  with_first_found:
    - metadata/saml20-idp-hosted-{{ ssp_major_version }}.{{ ssp_minor_version }}.php.j2
    - metadata/saml20-idp-hosted-{{ ssp_major_version }}.php.j2
    - metadata/saml20-idp-hosted.php.j2
  become: true
  tags:
    - ssp:config:saml20-idp-hosted
