---

- name: Check if SSP path exists
  stat:
    path: "{{ ssp_path }}"
  register: release_downloaded
  tags:
    - ssp:install:release

- block:

    - name: Create temp SSP installation directory
      tempfile:
        state: directory
      register: ssp_basepath

    - name: Download and unarchive SSP release into temp installation directory
      unarchive:
        src: "{{ ssp_release_url }}"
        dest: "{{ ssp_basepath.path }}/"
        owner: "root"
        group: "root"
        list_files: true
        remote_src: true

    - name: Ensure SSP path exists
      file:
        path: "{{ ssp_path }}"
        state: directory
        owner: "root"
        group: "root"

    - name: Copy release to SSP path
      copy:
        src: "{{ ssp_basepath.path }}/{{ ssp_repo_version }}/"
        dest: "{{ ssp_path }}"
        remote_src: true

    - name: Remove temp SSP installation directory
      file:
        path: "{{ ssp_basepath.path }}"
        state: absent

  when: release_downloaded.stat.exists == False
  become: yes
  tags:
    - ssp:install:release