---

- name: Checkout SSP source
  git:
    repo: "{{ ssp_repo_url }}"
    dest: "{{ ssp_path }}"
    version: "{{ ssp_repo_version }}"
    accept_hostkey: yes
    force: no
    update: no
  become: yes
  tags:
    - ssp:install:common

- name: Update symbolic link to SSP
  file:
    src: "{{ ssp_path }}/public/"
    dest: "{{ ssp_www_path }}"
    state: link
  become: yes
  tags:
    - ssp:install:common

- include_tasks: composer.yml
  when: (ssp_composer_install is defined) and (ssp_composer_install|bool == True)

- name: Change ownership of simplesamlphp directory
  file:
    state: directory
    owner: "{{ os_default_user }}"
    group: "{{ os_default_user }}"
    recurse: yes
    path: "{{ ssp_path }}"
  become: yes
  when: (ssp_install is defined) and (ssp_install|bool == True)
  tags:
    - ssp:install:common

- name: Install/Update SimplesamlPHP
  community.general.composer:
    command: update
    working_dir: "{{ ssp_path }}"
    ignore_platform_reqs: true
    no_scripts: true
  become: true
  become_user: "{{ os_default_user }}"
  when: (ssp_install is defined) and (ssp_install|bool == True)
  tags:
    - ssp:install:common

- include_tasks: twig.yml
  when: (twig_install is defined) and (twig_install|bool == True)

- name: Ensure SSP config dir exists
  file: path={{ ssp_configdir }} state=directory
  become: yes
  tags:
    - ssp:install:common

- name: Ensure SSP logging dir exists
  file:
    state: directory
    path: "{{ ssp_loggingdir }}"
    owner: "{{ ssp_webuser }}"
    group: "{{ ssp_webgroup }}"
    mode: "0750"
  become: yes
  tags:
    - ssp:install:common

- name: Ensure SSP data dir exists
  file: path={{ ssp_datadir }} state=directory
  become: yes
  tags:
    - ssp:install:common

- name: Ensure SSP metadata dir exists
  file: path={{ ssp_metadatadir }} state=directory
  become: yes
  tags:
    - ssp:install:common

- name: Ensure SSP cert dir exists
  file: path={{ ssp_certdir }} state=directory
  become: yes
  tags:
    - ssp:install:common

- name: Change ownership of simplesamlphp directory
  file:
    state: directory
    owner: "root"
    group: "root"
    recurse: yes
    path: "{{ ssp_path }}"
  become: yes
  when: (ssp_install is defined) and (ssp_install|bool == True)
  tags:
    - ssp:install:common
