---

- include_tasks: install-release.yml
  when: ssp_release_url is defined
  tags:
    - ssp:install

- include_tasks: install-source.yml
  when: ssp_release_url is not defined
  tags:
    - ssp:install

- name: Update symbolic link to SSP
  file:
    src: "{{ ssp_path }}/{{ 'public' if ssp_major_version == '2' else 'www' }}/"
    dest: "{{ ssp_www_path }}"
    state: link
  become: yes
  tags:
    - ssp:install

- include_tasks: twig.yml
  when: (ssp_twig_install is defined) and (ssp_twig_install|bool == True)

- name: Ensure SSP config dir exists
  file: path={{ ssp_configdir }} state=directory
  become: yes
  tags:
    - ssp:install

- name: Ensure SSP logging dir exists
  file:
    state: directory
    path: "{{ ssp_loggingdir }}"
    owner: "{{ ssp_webuser }}"
    group: "{{ ssp_webgroup }}"
    mode: "0750"
  become: yes
  tags:
    - ssp:install

- name: Ensure SSP data dir exists
  file: path={{ ssp_datadir }} state=directory
  become: yes
  tags:
    - ssp:install

- name: Ensure SSP metadata dir exists
  file: path={{ ssp_metadatadir }} state=directory
  become: yes
  tags:
    - ssp:install

- name: Ensure SSP cert dir exists
  file: path={{ ssp_certdir }} state=directory
  become: yes
  tags:
    - ssp:install

