---

- name: Checkout SSP source
  git:
    repo: "{{ ssp_repo_url }}"
    dest: "{{ ssp_path }}"
    version: "{{ ssp_repo_version }}"
    accept_hostkey: yes
    force: no
    update: no
  become: yes
  when: ssp_release_file is not defined
  tags:
    - ssp:install:source

- include_tasks: composer.yml
  when: (ssp_composer_install is defined) and (ssp_composer_install|bool == True)

- name: Install/Update SimplesamlPHP
  composer:
    command: update
    working_dir: "{{ ssp_path }}"
    composer_executable: "{{ ssp_composer_executable }}"
    ignore_platform_reqs: true
    no_scripts: true
  become: true
  tags:
    - ssp:install:source