---
- name: Check if SSP path exists
  ansible.builtin.stat:
    path: "{{ ssp_path }}"
  register: release_downloaded
  tags:
    - ssp:install:release

- name: SSP Install
  when: not release_downloaded.stat.exists
  become: true
  tags:
    - ssp:install:release
  block:
    - name: Create temp SSP installation directory
      ansible.builtin.tempfile:
        state: directory
      register: ssp_basepath

    - name: Download and unarchive SSP release into temp installation directory
      ansible.builtin.unarchive:
        src: "{{ ssp_release_url }}"
        dest: "{{ ssp_basepath.path }}/"
        owner: root
        group: root
        list_files: true
        remote_src: true

    - name: Ensure SSP path exists
      ansible.builtin.file:
        path: "{{ ssp_path }}"
        state: directory
        owner: root
        group: root
        mode: "0750"

    - name: Copy release to SSP path
      ansible.builtin.copy:
        src: "{{ ssp_basepath.path }}/{{ ssp_repo_version }}/"
        dest: "{{ ssp_path }}"
        remote_src: true
        mode: "0600"

    - name: Remove temp SSP installation directory
      ansible.builtin.file:
        path: "{{ ssp_basepath.path }}"
        state: absent
