---
- name: Ensure rsyslog & rsyslog-pgsql is installed (Debian)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
  loop: # TODO - define in defaults
    - rsyslog
    - rsyslog-pgsql
  become: true
  when: rsyslog_pgsql_enable_logs
