# file: tomcat/defaults/main.yml
#
---

# Override default tomcat version
# See tomcat_default_version defined in tomcat/vars/
# tomcat_version: "9"

# Override default tomcat service name
# See tomcat_default_service defined in tomcat/vars/
# tomcat_service: "tomcat{{ tomcat_version }}"

# Override default tomcat configuration path
# See tomcat_default_conf_path defined in tomcat/vars/
# tomcat_conf_path: "/etc/tomcat{{ tomcat_version }}"

# Override default tomcat JAVA_HOME
# See tomcat_default_java_home defined in tomcat/vars/
# tomcat_java_home: "/usr/lib/jvm/java-11-openjdk"

tomcat_java_opts: "-Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC"

tomcat_connectors:
  - port: 8080
    protocol: "HTTP/1.1"
    connection_timeout: 20000
    # executor: "tomcatThreadPool"
    # proxy_port: "443"
    redirect_port: 8443
    # scheme: "https"
    uri_encoding: UTF-8

tomcat_cluster_mode: false

# Uncomment to configure tomcat cluster parameters when tomcat_cluster_mode is set to true
# tomcat_cluster:
#  channel_send_options: "8"
#  channel_start_options: "3"
#  expire_sessions_on_shutdown: "false"
#  notify_listeners_on_replication: "true"
#  receiver:
#    address: "192.168.10.1"
#    auto_bind: "100"
#    max_threads: "6"
#    port: "4100"
#    selector_timeout: "5000"
#  interceptor_static_only: "true"
#  members:
#    - host: "192.168.10.2"
#      port: "4100"
#      unique_id: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,2"

# webapp_github_repo: "<USERNAME>/<PROJECT>"
# webapp_github_repo_token: "secret"
# webapp_github_release_file: "<FILENAME>"
# webapp_github_release_version: "<RELEASE_VERSION>"
# webapp_download_path: "/tmp"
# webapp_context_path: "<TEMP_DIR>"
# webapp_file: "<FILENAME_IN_DESTINATION>"
# webapp_path: "/var/lib/tomcat{{tomcat_version}}/webapps"
