---
# git/tasks/install-Debian.yml
- name: Update package cache (Debian)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  become: true

- name: Ensure latest Git is installed (Debian)
  ansible.builtin.apt:
    name: git
    state: present
    install_recommends: false
  become: true
