---
memcached_log_file: "/var/log/memcached.log"
# Log verbosity levels:
# `""`   Don't log anything (Default)
# `-v`   Be verbose during the event loop; print out errors and warnings.
# `-vv`  Be even more verbose; same as -v but also print client commands and
#        responses.
# `-vvv` Be  extremely verbose; same as -vv but also print internal state
#        transitions.
memcached_log_verbosity: ""

# Max memory (in MB) to use for object storage.
memcached_memory_max: 64

# TCP port to listen on
memcached_listen_port_tcp: 11211
# UDP port to listen on; 0 disables UDP.
memcached_listen_port_udp: 11211

# IP address to listen on; the default is to listen on all IP addresses.
# Binding to an internal or firewalled network interface is suggested.
# memcached_listen_address: 127.0.0.1

# Max number of simultaneous connections.
memcached_connections_max: 1024
