---
- name: Start keycloak
  ansible.builtin.systemd:
    name: keycloak
    state: started
  become: true

- name: Stop keycloak
  ansible.builtin.systemd:
    name: keycloak
    state: stopped
  become: true

- name: Restart keycloak
  ansible.builtin.systemd:
    name: keycloak
    state: restarted
  become: true

- name: Reload keycloak
  ansible.builtin.systemd:
    name: keycloak
    state: restarted
    daemon_reload: true
  become: true

- name: Clear Keycloak cache
  ansible.builtin.file:
    path: "{{ keycloak_home }}/data/tmp/"
    state: absent
  become: true
