---

- name: Start keycloak
  systemd:
    name: keycloak
    state: started
  become: yes

- name: Stop keycloak
  systemd:
    name: keycloak
    state: stopped
  become: yes

- name: Restart keycloak
  systemd:
    name: keycloak
    state: restarted
  become: yes

- name: Reload keycloak
  systemd:
    name: keycloak
    state: restarted
    daemon_reload: yes
  become: yes

- name: Clear Keycloak cache
  ansible.builtin.file:
    path: "{{ keycloak_home }}/data/tmp/"
    state: absent
  become: yes