---
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - curl
      - git
      - nginx

- name: Add node repository # noqa no-changed-when
  ansible.builtin.shell: >
    set -o pipefail
    curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
  args:
    warn: false

- name: Install node and npm
  ansible.builtin.apt:
    pkg:
      - build-essential
      - nodejs
      - npm

- name: Install pm2
  community.general.npm:
    name: pm2
    global: true
