# file: ssp-modules/tasks/configure-common.php
#
---


- name: Configure SSP modules
  template:
    src: "{{ item.src_config_path }}"
    dest: "{{ item.dest_config_path }}"
    backup: yes
    force: yes
  become: yes
  with_items: "{{ ssp_mods_extra_enabled }}"
  when: item.src_config_path is defined and item.dest_config_path is defined

- name: Register ssp version to ssp_version_num
  set_fact:
    ssp_version_num: "{{ssp_version.split('.')[:2] | join('.')| float}}"
    cacheable: yes
  become: yes
  tags:
    - ssp-modules:config:enable

- name: Preview ssp_version_num
  debug:
    msg: "{{ ssp_version_num }}"
  tags:
    - ssp-modules:config:enable

- name: Enable SSP modules
  copy:
    content: ""
    dest: "{{ item.path }}/enable"
    force: no
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes
  with_items: "{{ ssp_mods_extra_enabled }}"
  when: "{{ ssp_version_num|float < 2}}"
  tags:
    - ssp-modules:config:enable


- name: Ensure SSP module extra files are copied
  copy:
    src: "{{ item.src_path }}"
    dest: "{{ item.dest_path }}"
    backup: yes
  with_items: "{{ ssp_mods_extra_files }}"
  when: item.src_path is defined and item.dest_path is defined
  become: yes
  tags:
    - ssp-modules:config:files


- name: About Themes
  debug:
    msg:
      - The role also installs Themes, but doesn't produce the CSS files.
      - To produce them, you must install `sass` and follow the installation instructions for each theme.
