---

- name: "Get list of idps"
  ansible.builtin.uri:
    url: "{{ keycloak_proxy_host }}/admin/realms/{{ item[0].name }}/identity-provider/instances"
    method: GET
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
    status_code: 200
  register: "idps_result"

- name: Set fact
  ansible.builtin.set_fact:
    idps_list: "{{ idps_result.json | json_query('[].alias') }}"
