---

- name: Update package cache (Debian)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  become: true

- name: Ensure dirmngr is installed (Debian)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
  with_items:
    - dirmngr
  become: true
