# file: tomcat/tasks/install-Debian.yml
#
---
- name: Ensure Tomcat is installed (Debian)
  ansible.builtin.apt:
    name: "{{ tomcat_package }}"
    state: present
    update_cache: true
    cache_valid_time: 86400
    install_recommends: false
  become: true
