---
- name: Clear cache of COmanage
  ansible.builtin.command: su {{ comanage_registry_plugins_webuser }} -s /bin/sh -c ./Console/clearcache
  args:
    chdir: "{{ comanage_path }}/app"
  changed_when: false
  become: true
  become_user: "{{ comanage_registry_plugins_webuser }}"

- name: Ensure COmanage Registry local/Plugins directory exists
  ansible.builtin.file:
    path: "{{ comanage_path }}/local/Plugin"
    state: directory
    owner: root
    group: root
    mode: "0644"
  become: true

- name: "Ensure is cloned under local/Plugins directory - {{ item.name }}"
  ansible.builtin.git:
    repo: "{{ item.repository }}"
    dest: "{{ comanage_path }}/local/Plugin/{{ item.name }}"
    version: "{{ item.version }}"
    accept_hostkey: true
  become: true

- name: Create COmanage Registry Plugins schemata
  ansible.builtin.shell: |
    set -o pipefail
    ./Console/cake \
      schema create \
      --file schema.php \
      --path "{{ comanage_path }}/local/Plugin/{{ item.name }}/Config/Schema" \
      -y
  args:
    chdir: "{{ comanage_path }}/app"
    executable: /bin/sh
  when: item.status is defined and item.status == "init"
  changed_when: false # TODO Define change conditions
  become: true
