---
- name: Configure timezone
  ansible.builtin.template:
    src: etc/timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - Update timezone
