---
- name: Update package cache (Debian)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  become: true

- name: Ensure common packages are installed (Debian)
  ansible.builtin.apt:
    pkg:
      - aptitude
      - ca-certificates
      - vim-nox
    state: present
    install_recommends: false
  become: true
