---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'
# - include: install-CentOS.yml
#  when: ansible_os_family == 'CentOS'

# Run OS-independent installation tasks
# - include: install-common.yml

- name: Apply OS-specific configuration
  ansible.builtin.include_tasks: configure-Debian.yml
  when: ansible_os_family == 'Debian'
# - include: configure-CentOS.yml
#  when: ansible_os_family == 'CentOS'

- name: Apply OS-independent configuration
  ansible.builtin.include_tasks: configure-common.yml
