---

apache_http_port: 80
apache_https_port: 443

apache_listen_directives: |
  Listen {{ apache_http_port }}

  <IfModule ssl_module>
    Listen {{ apache_https_port }}
  </IfModule>

  <IfModule mod_gnutls.c>
    Listen {{ apache_https_port }}
  </IfModule>

# Set to one of:  Full | OS | Minimal | Minor | Major | Prod
# where Full conveys the most information, and Prod the least.
apache_server_tokens: "OS"
# Set to one of:  On | Off | EMail
# Set to "EMail" to also include a mailto: link to the ServerAdmin.
apache_server_signature: "On"
# Set to one of:  On | Off | extended
apache_trace_enable: "Off"

apache_create_vhosts: true
apache_vhosts_filename: "vhosts.conf"
# On RedHat/Centos, a default Welcome Screen is included in Apache's configuration.
# Set this to `true` to remove that default; otherwise `false`.
apache_remove_default_page: false

# On Debian/Ubuntu, a default virtualhost is included in Apache's configuration.
# Set this to `true` to remove that default; otherwise `false`.
apache_remove_default_vhost: true

apache_vhosts:
  # Additional properties: `serveradmin`, `serveralias`, `usecanonicalname`,
  # `extra_parameters`.
  - servername: "{{ inventory_hostname }}"
    documentroot: "/var/www/html"

apache_vhosts_ssl: []
  # Additional properties: `serveradmin`, `serveralias`, `usecanonicalname`,
  # `extra_parameters`.
  # - servername: "www.example.com"
  #   documentroot: "/var/www/html"
  #   certificate_file: "/path/to/certificate.crt"
  #   certificate_key_file: "/path/to/certificate.key"
  #   # Optional.
  #   certificate_chain_file: "/path/to/certificate_chain.crt"

# Name of the user that should own the file containing the SSL certificate
apache_ssl_certificate_file_owner: "root"
# Name of the group that should own the file containing the SSL certificate
apache_ssl_certificate_file_group: "root"
# Permissions of the file containing the SSL certificate
apache_ssl_certificate_file_mode: "0644"

# Name of the user that should own the file containing the SSL certificate key
apache_ssl_certificate_key_file_owner: "root"
# Name of the group that should own the file containing the SSL certificate key
apache_ssl_certificate_key_file_group: "root"
# Permissions of the file containing the SSL certificate key
apache_ssl_certificate_key_file_mode: "0600"

apache_ignore_missing_ssl_certificate: true

# apache_ssl_protocol: "All -SSLv2 -SSLv3"
# apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"

# Initial apache state, i.e. `started`, `stopped`, `restarted`, or `reloaded`
apache_state: "started"

# install additional modules
apache_mods_installed: []

# Only used on Debian/Ubuntu.
apache_mods_enabled:
  - ssl
apache_mods_disabled: []
