---
- name: Ensure PHP configuration files exist
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ php_conf_scan_dir }}/"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ php_conf_files }}"
  become: true
  notify:
    - restart webserver
