---
- name: Install apt packages required for alternative PHP repo (Debian)
  ansible.builtin.apt:
    name: "{{ php_apt_packages }}"
    state: present
    update_cache: true
  when: php_alt_repo and php_apt_packages is defined and php_apt_packages|length
  become: true

- name: Install apt key for PHP repo (Debian)
  ansible.builtin.apt_key:
    url: "{{ php_apt_key }}"
    state: present
  when: php_alt_repo and php_apt_key is defined
  become: true

- name: Add alternative PHP repo (Debian)
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
    filename: php
  loop: "{{ php_apt_repositories }}"
  when: php_alt_repo and php_apt_repositories is defined and php_apt_repositories|length
  become: true

- name: Ensure PHP packages are installed (Debian)
  ansible.builtin.apt:
    name: "{{ php_packages }}"
    state: present
    update_cache: true
    install_recommends: false
  become: true
  notify:
    - restart webserver

- name: Ensure PHP extensions are installed (Debian)
  ansible.builtin.apt:
    pkg: "{{ php_extensions }}"
    state: present
    update_cache: true
    install_recommends: false
  become: true
  notify:
    - restart webserver
