---
- name: Ensure Repositories are installed (RedHat)
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop: "{{ php_yum_repositories }}"
  when: php_alt_repo and php_yum_repositories is defined and php_yum_repositories|length
  become: true

- name: Import remi GPG key.
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  loop: "{{ php_yum_keys }}"
  when: php_alt_repo and php_yum_repositories is defined and php_yum_repositories|length
  become: true

- name: Ensure PHP packages are installed (RedHat)
  ansible.builtin.yum:
    enablerepo: remi,remi-safe,remi-php{{ php_version }}
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop: "{{ php_packages }}"
  when: php_alt_repo and php_yum_repositories is defined and php_yum_repositories|length
  notify:
    - restart webserver

- name: Ensure PHP packages are installed (default repo) (RedHat)
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop: "{{ php_packages }}"
  when: not php_alt_repo and php_yum_repositories is not defined
  notify:
    - restart webserver

- name: Ensure PHP extensions are installed (RedHat)
  ansible.builtin.yum:
    enablerepo: remi,remi-safe,remi-php{{ php_version }}
    name: "{{ php_extensions }}"
    state: present
    update_cache: true
  become: true
  loop: "{{ php_extensions | default([]) }}"
  when: php_alt_repo and php_yum_repositories is defined and php_yum_repositories|length
  notify:
    - restart webserver

- name: Ensure PHP extensions are installed (default repo) (RedHat)
  ansible.builtin.yum:
    name: "{{ php_extensions }}"
    state: present
    update_cache: true
  become: true
  loop: "{{ php_extensions | default([]) }}"
  when: not php_alt_repo and php_yum_repositories is not defined
  notify:
    - restart webserver
