---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Define PHP packages
  ansible.builtin.set_fact:
    php_packages: "{{ php_default_packages | list }}"
  when: php_packages is not defined

- name: Define PHP configuration scan dir
  ansible.builtin.set_fact:
    php_conf_scan_dir: "{{ php_default_conf_scan_dir }}"
  when: php_conf_scan_dir is not defined

# Include OS-specific installation tasks
- name: Include Debian Install Tasks
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'
- name: Include RedHat Install Tasks
  ansible.builtin.include_tasks: install-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Could be refactored

# Include OS-independent configuration tasks
- name: Include Configure Tasks
  ansible.builtin.include_tasks: configure.yml
