---
- name: Install OS-specific packages
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'
# - include: install-CentOS.yml
#  when: ansible_os_family == 'CentOS'
