---
- name: Ensure memcached service is configured
  ansible.builtin.template:
    src: memcached-{{ ansible_os_family }}.conf.j2
    dest: "{{ memcached_config_file }}"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart memcached
