---

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: OS-specific installation tasks
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

- name: OS-independent installation tasks
  ansible.builtin.include_tasks: install-common.yml

- name: Apply OS-independent configuration
  ansible.builtin.include_tasks: configure-common.yml

- name: Ensure memcached service is at selected state and enabled on boot
  ansible.builtin.service:
    name: memcached
    state: started
    enabled: true
  become: true
