---
# postgresql
- name: Reload PostgreSQL
  ansible.builtin.service:
    name: "{{ postgresql_service }}"
    state: "reloaded"
  become: true

- name: Restart PostgreSQL
  ansible.builtin.service:
    name: "{{ postgresql_service }}"
    state: restarted
  become: true
