# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  pull_request:
    branches: ["devel", "master"]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ansible_lint_version:
          - v6.22.2
          - v24.2.1
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@${{ matrix.ansible_lint_version}}
