# file: keycloak/vars/15.yml
#
---

namespaces:
  domain: "urn:jboss:domain:16.0"
  domain_server: "urn:jboss:domain:keycloak-server:1.1"

keycloak_api:
  terms_and_conditions:
    endpoint: "terms_and_conditions"
    alias: "terms_and_conditions"
    provider_id: "terms_and_conditions"
